name: 'multiproject-infracost-review'
description: 'This action generates cost estimates for CDKTF-based multi-project infrastructure using Infracost and automatically posts the results as comments in GitHub pull requests'
author: 'heavywater-dev'
inputs:
  infracost-api-key:
    description: 'Your Infracost API key. You can get one for free at https://infracost.io/signup/'
    required: true
  path:
    description: 'The path to the directory containing your CDKTF projects.'
    required: false
    default: 'infra'
  cdktf:
    description: 'Whether to use CDKTF (true) or plain Terraform (false).'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub token used to post comments on pull requests.'
    required: true
  pull-request-base:
    description: 'The base branch for the pull request.'
    required: true
  github-repository:
    description: 'Repository slug (owner/repo).'
    required: true
  pull-request-number:
    description: 'Pull request number to comment on.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate cdktf input
      run: |
        if [[ "${{ inputs.cdktf }}" != "true" && "${{ inputs.cdktf }}" != "false" ]]; then
          echo "Error: input 'cdktf' must be either 'true' or 'false'."
          exit 1
        fi
      shell: bash

    - name: Setup Infracost
      uses: infracost/actions/setup@v3
      with:
        api-key: ${{ inputs.infracost-api-key }}

    - name: Setup jq for JSON processing
      run: |
        if ! command -v jq &> /dev/null; then
          echo "Installing jq..."
          sudo apt-get update && sudo apt-get install -y jq
        else
          echo "jq already installed"
        fi
      shell: bash

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm

    - name: Checkout base branch
      uses: actions/checkout@v5
      with:
        ref: '${{ inputs.pull-request-base }}'

    - name: add rules for all scripts
      run: |
        chmod -R +x ${{ github.action_path }}/scripts
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Synth tf files for baseline
      run: |
        ${{ github.action_path }}/scripts/synth-tf-files.sh "${{ inputs.path }}" "${{ inputs.cdktf }}"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Generate Infracost cost estimate for baseline
      run: |
        ${{ github.action_path }}/scripts/generate_infracost_estimate.sh "${{ inputs.path }}" "/tmp/infracost-base.json"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Checkout PR branch
      uses: actions/checkout@v5

    - name: Synth tf files for PR
      run: |
        ${{ github.action_path }}/scripts/synth-tf-files.sh "${{ inputs.path }}" "${{ inputs.cdktf }}"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Generate Infracost cost estimate for PR
      run: |
        ${{ github.action_path }}/scripts/generate_infracost_estimate.sh "${{ inputs.path }}" "/tmp/infracost-pr.json"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Generate Infracost diff
      run: |
        ${{ github.action_path }}/scripts/generate_infracost_diff.sh \
          --base-file "/tmp/infracost-base.json" \
          --head-file "/tmp/infracost-pr.json" \
          --out-file "/tmp/infracost-diff.json"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Post Infracost comment to PR
      run: |
        ${{ github.action_path }}/scripts/generate_infracost_comment.sh \
          --repo "${{ inputs.github-repository }}" \
          --github-token "${{ inputs.github-token }}" \
          --pull-request "${{ inputs.pull-request-number }}" \
          --diff-file "/tmp/infracost-diff.json"
      shell: bash
      working-directory: ${{ github.workspace }}
